In [1]:
# encoding=utf8

# 特征工程案例

Kaggle上有这样一个比赛：城市自行车共享系统使用状况。https://www.kaggle.com/c/bike-sharing-demand/data

提供的数据为2年内按小时做的自行车租赁数据，其中训练集由每个月的前19天组成，测试集由20号之后的时间组成。

In [2]:
import pandas as pd
data = pd.read_csv('../../DataSets/competition/kaggle/Bike-Sharing-Demand/kaggle_bike_competition_train.csv', header = 0, error_bad_lines=False)

In [3]:
data.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3  2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4  2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1

In [3]:

temp = pd.DatetimeIndex(data['datetime'])
data['date'] = temp.date
data['time'] = temp.time
data.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3  2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4  2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count        date      time  
0        81        0.0       3          13     16  2011-01-01  00:00:00  
1        80        0.0       8          32     40  2011-01-01  01:00:00  
2        80        0.0       5          27     32  2011-01-01  02:00:00  
3        75        0.0       3          10     13  2011-01-01  03:00:00  
4        75        0.0       0           1      1  2011-01-01  04:00:00

In [4]:

data['hour'] = pd.to_datetime(data.time, format="%H:%M:%S")
data['hour'] = pd.Index(data['hour']).hour
data

datetime  season  holiday  workingday  weather   temp  \
0      2011-01-01 00:00:00       1        0           0        1   9.84   
1      2011-01-01 01:00:00       1        0           0        1   9.02   
2      2011-01-01 02:00:00       1        0           0        1   9.02   
3      2011-01-01 03:00:00       1        0           0        1   9.84   
4      2011-01-01 04:00:00       1        0           0        1   9.84   
5      2011-01-01 05:00:00       1        0           0        2   9.84   
6      2011-01-01 06:00:00       1        0           0        1   9.02   
7      2011-01-01 07:00:00       1        0           0        1   8.20   
8      2011-01-01 08:00:00       1        0           0        1   9.84   
9      2011-01-01 09:00:00       1        0           0        1  13.12   
10     2011-01-01 10:00:00       1        0           0        1  15.58   
11     2011-01-01 11:00:00       1        0           0        1  14.76   
12     2011-01-01 12:00:00       1        0           0        1  17.22   
13     2011-01-01 13:00:00       1        0           0        2  18.86   
14     2011-01-01 14:00:00       1        0           0        2  18.86   
15     2011-01-01 15:00:00       1        0           0        2  18.04   
16     2011-01-01 16:00:00       1        0           0        2  17.22   
17     2011-01-01 17:00:00       1        0           0        2  18.04   
18     2011-01-01 18:00:00       1        0           0        3  17.22   
19     2011-01-01 19:00:00       1        0           0        3  17.22   
20     2011-01-01 20:00:00       1        0           0        2  16.40   
21     2011-01-01 21:00:00       1        0           0        2  16.40   
22     2011-01-01 22:00:00       1        0           0        2  16.40   
23     2011-01-01 23:00:00       1        0           0        2  18.86   
24     2011-01-02 00:00:00       1        0           0        2  18.86   
25     2011-01-02 01:00:00       1        0           0        2  18.04   
26     2011-01-02 02:00:00       1        0           0        2  17.22   
27     2011-01-02 03:00:00       1        0           0        2  18.86   
28     2011-01-02 04:00:00       1        0           0        2  18.86   
29     2011-01-02 06:00:00       1        0           0        3  17.22   
...                    ...     ...      ...         ...      ...    ...   
10856  2012-12-18 18:00:00       4        0           1        1  15.58   
10857  2012-12-18 19:00:00       4        0           1        1  15.58   
10858  2012-12-18 20:00:00       4        0           1        1  14.76   
10859  2012-12-18 21:00:00       4        0           1        1  14.76   
10860  2012-12-18 22:00:00       4        0           1        1  13.94   
10861  2012-12-18 23:00:00       4        0           1        1  13.94   
10862  2012-12-19 00:00:00       4        0           1        1  12.30   
10863  2012-12-19 01:00:00       4        0           1        1  12.30   
10864  2012-12-19 02:00:00       4        0           1        1  11.48   
10865  2012-12-19 03:00:00       4        0           1        1  10.66   
10866  2012-12-19 04:00:00       4        0           1        1   9.84   
10867  2012-12-19 05:00:00       4        0           1        1  10.66   
10868  2012-12-19 06:00:00       4        0           1        1   9.84   
10869  2012-12-19 07:00:00       4        0           1        1  10.66   
10870  2012-12-19 08:00:00       4        0           1        1   9.84   
10871  2012-12-19 09:00:00       4        0           1        1  11.48   
10872  2012-12-19 10:00:00       4        0           1        1  13.12   
10873  2012-12-19 11:00:00       4        0           1        1  16.40   
10874  2012-12-19 12:00:00       4        0           1        1  16.40   
10875  2012-12-19 13:00:00       4        0           1        1  17.22   
10876  2012-12-19 14:00:00       4        0           1        1  17.22   
10877  2012-12-19 15:00:00       4        0

In [5]:

data['dayofweek'] = pd.DatetimeIndex(data.date).dayofweek


data['dateDays'] = (data.date - data.date[0]).astype('timedelta64[D]')

data

datetime  season  holiday  workingday  weather   temp  \
0      2011-01-01 00:00:00       1        0           0        1   9.84   
1      2011-01-01 01:00:00       1        0           0        1   9.02   
2      2011-01-01 02:00:00       1        0           0        1   9.02   
3      2011-01-01 03:00:00       1        0           0        1   9.84   
4      2011-01-01 04:00:00       1        0           0        1   9.84   
5      2011-01-01 05:00:00       1        0           0        2   9.84   
6      2011-01-01 06:00:00       1        0           0        1   9.02   
7      2011-01-01 07:00:00       1        0           0        1   8.20   
8      2011-01-01 08:00:00       1        0           0        1   9.84   
9      2011-01-01 09:00:00       1        0           0        1  13.12   
10     2011-01-01 10:00:00       1        0           0        1  15.58   
11     2011-01-01 11:00:00       1        0           0        1  14.76   
12     2011-01-01 12:00:00       1        0           0        1  17.22   
13     2011-01-01 13:00:00       1        0           0        2  18.86   
14     2011-01-01 14:00:00       1        0           0        2  18.86   
15     2011-01-01 15:00:00       1        0           0        2  18.04   
16     2011-01-01 16:00:00       1        0           0        2  17.22   
17     2011-01-01 17:00:00       1        0           0        2  18.04   
18     2011-01-01 18:00:00       1        0           0        3  17.22   
19     2011-01-01 19:00:00       1        0           0        3  17.22   
20     2011-01-01 20:00:00       1        0           0        2  16.40   
21     2011-01-01 21:00:00       1        0           0        2  16.40   
22     2011-01-01 22:00:00       1        0           0        2  16.40   
23     2011-01-01 23:00:00       1        0           0        2  18.86   
24     2011-01-02 00:00:00       1        0           0        2  18.86   
25     2011-01-02 01:00:00       1        0           0        2  18.04   
26     2011-01-02 02:00:00       1        0           0        2  17.22   
27     2011-01-02 03:00:00       1        0           0        2  18.86   
28     2011-01-02 04:00:00       1        0           0        2  18.86   
29     2011-01-02 06:00:00       1        0           0        3  17.22   
...                    ...     ...      ...         ...      ...    ...   
10856  2012-12-18 18:00:00       4        0           1        1  15.58   
10857  2012-12-18 19:00:00       4        0           1        1  15.58   
10858  2012-12-18 20:00:00       4        0           1        1  14.76   
10859  2012-12-18 21:00:00       4        0           1        1  14.76   
10860  2012-12-18 22:00:00       4        0           1        1  13.94   
10861  2012-12-18 23:00:00       4        0           1        1  13.94   
10862  2012-12-19 00:00:00       4        0           1        1  12.30   
10863  2012-12-19 01:00:00       4        0           1        1  12.30   
10864  2012-12-19 02:00:00       4        0           1        1  11.48   
10865  2012-12-19 03:00:00       4        0           1        1  10.66   
10866  2012-12-19 04:00:00       4        0           1        1   9.84   
10867  2012-12-19 05:00:00       4        0           1        1  10.66   
10868  2012-12-19 06:00:00       4        0           1        1   9.84   
10869  2012-12-19 07:00:00       4        0           1        1  10.66   
10870  2012-12-19 08:00:00       4        0           1        1   9.84   
10871  2012-12-19 09:00:00       4        0           1        1  11.48   
10872  2012-12-19 10:00:00       4        0           1        1  13.12   
10873  2012-12-19 11:00:00       4        0           1        1  16.40   
10874  2012-12-19 12:00:00       4        0           1        1  16.40   
10875  2012-12-19 13:00:00       4        0           1        1  17.22   
10876  2012-12-19 14:00:00       4        0           1        1  17.22   
10877  2012-12-19 15:00:00       4        0

In [6]:
byday = data.groupby('dayofweek')

byday['casual'].sum().reset_index()

dayofweek  casual
0          0   46288
1          1   35365
2          2   34931
3          3   37283
4          4   47402
5          5  100782
6          6   90084

In [7]:

byday['registered'].sum().reset_index()

dayofweek  registered
0          0      249008
1          1      256620
2          2      257295
3          3      269118
4          4      255102
5          5      210736
6          6      195462

In [8]:
data['Saturday']=0
data.Saturday[data.dayofweek==5]=1

data['Sunday']=0
data.Sunday[data.dayofweek==6]=1

data

/Users/bater.makhabel/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Users/bater.makhabel/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


datetime  season  holiday  workingday  weather   temp  \
0      2011-01-01 00:00:00       1        0           0        1   9.84   
1      2011-01-01 01:00:00       1        0           0        1   9.02   
2      2011-01-01 02:00:00       1        0           0        1   9.02   
3      2011-01-01 03:00:00       1        0           0        1   9.84   
4      2011-01-01 04:00:00       1        0           0        1   9.84   
5      2011-01-01 05:00:00       1        0           0        2   9.84   
6      2011-01-01 06:00:00       1        0           0        1   9.02   
7      2011-01-01 07:00:00       1        0           0        1   8.20   
8      2011-01-01 08:00:00       1        0           0        1   9.84   
9      2011-01-01 09:00:00       1        0           0        1  13.12   
10     2011-01-01 10:00:00       1        0           0        1  15.58   
11     2011-01-01 11:00:00       1        0           0        1  14.76   
12     2011-01-01 12:00:00       1        0           0        1  17.22   
13     2011-01-01 13:00:00       1        0           0        2  18.86   
14     2011-01-01 14:00:00       1        0           0        2  18.86   
15     2011-01-01 15:00:00       1        0           0        2  18.04   
16     2011-01-01 16:00:00       1        0           0        2  17.22   
17     2011-01-01 17:00:00       1        0           0        2  18.04   
18     2011-01-01 18:00:00       1        0           0        3  17.22   
19     2011-01-01 19:00:00       1        0           0        3  17.22   
20     2011-01-01 20:00:00       1        0           0        2  16.40   
21     2011-01-01 21:00:00       1        0           0        2  16.40   
22     2011-01-01 22:00:00       1        0           0        2  16.40   
23     2011-01-01 23:00:00       1        0           0        2  18.86   
24     2011-01-02 00:00:00       1        0           0        2  18.86   
25     2011-01-02 01:00:00       1        0           0        2  18.04   
26     2011-01-02 02:00:00       1        0           0        2  17.22   
27     2011-01-02 03:00:00       1        0           0        2  18.86   
28     2011-01-02 04:00:00       1        0           0        2  18.86   
29     2011-01-02 06:00:00       1        0           0        3  17.22   
...                    ...     ...      ...         ...      ...    ...   
10856  2012-12-18 18:00:00       4        0           1        1  15.58   
10857  2012-12-18 19:00:00       4        0           1        1  15.58   
10858  2012-12-18 20:00:00       4        0           1        1  14.76   
10859  2012-12-18 21:00:00       4        0           1        1  14.76   
10860  2012-12-18 22:00:00       4        0           1        1  13.94   
10861  2012-12-18 23:00:00       4        0           1        1  13.94   
10862  2012-12-19 00:00:00       4        0           1        1  12.30   
10863  2012-12-19 01:00:00       4        0           1        1  12.30   
10864  2012-12-19 02:00:00       4        0           1        1  11.48   
10865  2012-12-19 03:00:00       4        0           1        1  10.66   
10866  2012-12-19 04:00:00       4        0           1        1   9.84   
10867  2012-12-19 05:00:00       4        0           1        1  10.66   
10868  2012-12-19 06:00:00       4        0           1        1   9.84   
10869  2012-12-19 07:00:00       4        0           1        1  10.66   
10870  2012-12-19 08:00:00       4        0           1        1   9.84   
10871  2012-12-19 09:00:00       4        0           1        1  11.48   
10872  2012-12-19 10:00:00       4        0           1        1  13.12   
10873  2012-12-19 11:00:00       4        0           1        1  16.40   
10874  2012-12-19 12:00:00       4        0           1        1  16.40   
10875  2012-12-19 13:00:00       4        0           1        1  17.22   
10876  2012-12-19 14:00:00       4        0           1        1  17.22   
10877  2012-12-19 15:00:00       4        0

In [9]:

dataRel = data.drop(['datetime', 'count','date','time','dayofweek'], axis=1)
dataRel.head()

season  holiday  workingday  weather  temp   atemp  humidity  windspeed  \
0       1        0           0        1  9.84  14.395        81        0.0   
1       1        0           0        1  9.02  13.635        80        0.0   
2       1        0           0        1  9.02  13.635        80        0.0   
3       1        0           0        1  9.84  14.395        75        0.0   
4       1        0           0        1  9.84  14.395        75        0.0   

   casual  registered  hour  dateDays  Saturday  Sunday  
0       3          13     0       0.0         1       0  
1       8          32     1       0.0         1       0  
2       5          27     2       0.0         1       0  
3       3          10     3       0.0         1       0  
4       0           1     4       0.0         1       0

In [10]:
from sklearn.feature_extraction import DictVectorizer

featureConCols = ['temp','atemp','humidity','windspeed','dateDays','hour']
dataFeatureCon = dataRel[featureConCols]
dataFeatureCon = dataFeatureCon.fillna( 'NA' ) #in case I missed any
X_dictCon = dataFeatureCon.T.to_dict().values() 


featureCatCols = ['season','holiday','workingday','weather','Saturday', 'Sunday']
dataFeatureCat = dataRel[featureCatCols]
dataFeatureCat = dataFeatureCat.fillna( 'NA' ) #in case I missed any
X_dictCat = dataFeatureCat.T.to_dict().values() 


vec = DictVectorizer(sparse = False)
X_vec_cat = vec.fit_transform(X_dictCat)
X_vec_con = vec.fit_transform(X_dictCon)

In [11]:
dataFeatureCon.head()

temp   atemp  humidity  windspeed  dateDays  hour
0  9.84  14.395        81        0.0       0.0     0
1  9.02  13.635        80        0.0       0.0     1
2  9.02  13.635        80        0.0       0.0     2
3  9.84  14.395        75        0.0       0.0     3
4  9.84  14.395        75        0.0       0.0     4

In [12]:
X_vec_con

array([[  14.395 ,    0.    ,    0.    ,   81.    ,    9.84  ,    0.    ],
       [  13.635 ,    0.    ,    1.    ,   80.    ,    9.02  ,    0.    ],
       [  13.635 ,    0.    ,    2.    ,   80.    ,    9.02  ,    0.    ],
       ..., 
       [  15.91  ,  718.    ,   21.    ,   61.    ,   13.94  ,   15.0013],
       [  17.425 ,  718.    ,   22.    ,   61.    ,   13.94  ,    6.0032],
       [  16.665 ,  718.    ,   23.    ,   66.    ,   13.12  ,    8.9981]])

In [13]:
dataFeatureCat.head()

season  holiday  workingday  weather  Saturday  Sunday
0       1        0           0        1         1       0
1       1        0           0        1         1       0
2       1        0           0        1         1       0
3       1        0           0        1         1       0
4       1        0           0        1         1       0

In [14]:
X_vec_cat

array([[ 1.,  0.,  0.,  1.,  1.,  0.],
       [ 1.,  0.,  0.,  1.,  1.,  0.],
       [ 1.,  0.,  0.,  1.,  1.,  0.],
       ..., 
       [ 0.,  0.,  0.,  4.,  1.,  1.],
       [ 0.,  0.,  0.,  4.,  1.,  1.],
       [ 0.,  0.,  0.,  4.,  1.,  1.]])

In [15]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(X_vec_con)
X_vec_con = scaler.transform(X_vec_con)
X_vec_con

array([[-1.09273697, -1.70912256, -1.66894356,  0.99321305, -1.33366069,
        -1.56775367],
       [-1.18242083, -1.70912256, -1.52434128,  0.94124921, -1.43890721,
        -1.56775367],
       [-1.18242083, -1.70912256, -1.379739  ,  0.94124921, -1.43890721,
        -1.56775367],
       ..., 
       [-0.91395927,  1.70183906,  1.36770431, -0.04606385, -0.80742813,
         0.26970368],
       [-0.73518157,  1.70183906,  1.51230659, -0.04606385, -0.80742813,
        -0.83244247],
       [-0.82486544,  1.70183906,  1.65690887,  0.21375537, -0.91267464,
        -0.46560752]])

In [16]:
from sklearn import preprocessing
# one-hot
enc = preprocessing.OneHotEncoder()
enc.fit(X_vec_cat)
X_vec_cat = enc.transform(X_vec_cat).toarray()
X_vec_cat

array([[ 0.,  1.,  1., ...,  0.,  1.,  0.],
       [ 0.,  1.,  1., ...,  0.,  1.,  0.],
       [ 0.,  1.,  1., ...,  0.,  1.,  0.],
       ..., 
       [ 1.,  0.,  1., ...,  0.,  0.,  1.],
       [ 1.,  0.,  1., ...,  0.,  0.,  1.],
       [ 1.,  0.,  1., ...,  0.,  0.,  1.]])

In [17]:
import numpy as np
# combine cat & con features
X_vec = np.concatenate((X_vec_con,X_vec_cat), axis=1)
X_vec

array([[-1.09273697, -1.70912256, -1.66894356, ...,  0.        ,
         1.        ,  0.        ],
       [-1.18242083, -1.70912256, -1.52434128, ...,  0.        ,
         1.        ,  0.        ],
       [-1.18242083, -1.70912256, -1.379739  , ...,  0.        ,
         1.        ,  0.        ],
       ..., 
       [-0.91395927,  1.70183906,  1.36770431, ...,  0.        ,
         0.        ,  1.        ],
       [-0.73518157,  1.70183906,  1.51230659, ...,  0.        ,
         0.        ,  1.        ],
       [-0.82486544,  1.70183906,  1.65690887, ...,  0.        ,
         0.        ,  1.        ]])

In [18]:

Y_vec_reg = dataRel['registered'].values.astype(float)
Y_vec_cas = dataRel['casual'].values.astype(float)

In [19]:

Y_vec_reg

array([  13.,   32.,   27., ...,  164.,  117.,   84.])

In [20]:
Y_vec_cas

array([  3.,   8.,   5., ...,   4.,  12.,   4.])