In [1]:
# encoding=utf8

# Pandas


# Getting Started with pandas

In [21]:
import pandas as pd

In [22]:
from pandas import Series, DataFrame

In [23]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## Introduction to pandas Data Structures

### Series

In [24]:
# create and initializae a pandas series
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [26]:
# check the variable type and print single value by index from 0 to length - 1
type(obj),obj[0],obj[1],obj[2],obj[3],len(obj)

(pandas.core.series.Series, 4, 7, -5, 3, 4)

In [29]:
# the internal values are stored with numpy.ndarray
obj.values, type(obj.values)


(array([ 4,  7, -5,  3]), numpy.ndarray)

In [35]:
# the index for pandas series are stored with value in the type of pandas.indexes.range.RangeIndex
print(type(obj.index))
print(obj.index )

<class 'pandas.indexes.range.RangeIndex'>
RangeIndex(start=0, stop=4, step=1)


In [36]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
print(obj2)
print(obj2.index)

d    4
b    7
a   -5
c    3
dtype: int64
Index(['d', 'b', 'a', 'c'], dtype='object')


In [37]:
print(obj2['a'])
obj2['d'] = 6
print(obj2[['c', 'a', 'd']])

-5
c    3
a   -5
d    6
dtype: int64


In [45]:
# boolean selection
print(obj2)
print(obj2[obj2 > 0])
print(obj2[(obj2 > 0) & (obj2 <7)])

d    6
b    7
a   -5
c    3
dtype: int64
d    6
b    7
c    3
dtype: int64
d    6
c    3
dtype: int64


In [47]:
# multiply a pandas series with an scale value, which apply the operation to each element of th series
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [48]:
# numpy builtin function exponent
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [54]:
# membership by index key
'b' in obj2,'e' in obj2, obj2['b']
# try to run the following statement, index with the key 'e', :D
# obj2['e']

(True, False, 7)

In [56]:
# create and initialize a pandas series with a python dictionary
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
print(sdata)
print(type(sdata))
print(obj3)

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
<class 'dict'>
Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64


In [59]:
# create and initialize a pandas series with a python list, and set the index for the series with a python list too
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
print(obj4)

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64


In [60]:
# check which value of the pandas series variable is null by pandas.isnull
# which return with a variable in the type of "pandas.core.series.Series"
pd.isnull(obj4),type(pd.isnull(obj4))

(California     True
 Ohio          False
 Oregon        False
 Texas         False
 dtype: bool, pandas.core.series.Series)

In [62]:
# check which value of the pandas series variable is not null by pandas.notnull
# which return with a variable in the type of "pandas.core.series.Series"

pd.notnull(obj4),type(pd.notnull(obj4))

(California    False
 Ohio           True
 Oregon         True
 Texas          True
 dtype: bool, pandas.core.series.Series)

In [65]:
# boolean selection
obj4[pd.isnull(obj4)]

California   NaN
dtype: float64

In [66]:
# boolean selection
obj4[pd.notnull(obj4)]

Ohio      35000.0
Oregon    16000.0
Texas     71000.0
dtype: float64

In [68]:
# boolean selection
print(obj4.isnull())
print(obj4[obj4.isnull()])

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool
California   NaN
dtype: float64


In [70]:
# Addition of two pandas series
print(obj3)
print(obj4)
print(obj3 + obj4)

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64


In [71]:
# index naming
obj4.name = 'population'
obj4.index.name = 'state'
print(obj4)

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64


In [72]:
# set index for pandas series variable
print(obj)
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64
Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64


### DataFrame

In [74]:
# create and initialize an pandas data frame variable with a python dicdtionary
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame.head()

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [75]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [76]:
# get the statistical properties for numerical column of the pandas data frame variable
frame.describe()

pop         year
count  6.000000     6.000000
mean   2.550000  2001.500000
std    0.836062     1.048809
min    1.500000  2000.000000
25%    1.875000  2001.000000
50%    2.650000  2001.500000
75%    3.125000  2002.000000
max    3.600000  2003.000000

In [78]:
# get the first N=3 rows from the pandas data frame variable
frame.head(3)

pop state  year
0  1.5  Ohio  2000
1  1.7  Ohio  2001
2  3.6  Ohio  2002

In [80]:
# create and initialize an pandas data frame variable with a python dictionary
print(data)
print(type(data))
pd.DataFrame(data, columns=['year', 'state', 'pop'])

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002, 2003], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
<class 'dict'>


year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [99]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
print(frame2)
print(frame2.columns)
print(type(frame2.columns))

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN
Index(['year', 'state', 'pop', 'debt'], dtype='object')
<class 'pandas.indexes.base.Index'>


In [100]:
# fetch an element by column name
print(frame2['state'])


one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object


In [101]:
# fetch an element by column name
print(frame2.year)

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64


In [102]:
# fetch an row by index value
print(frame2.loc['three'])
print(type(frame2.loc['three']))

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object
<class 'pandas.core.series.Series'>


In [103]:
# assign values by column
print(frame2)
frame2['debt'] = 16.5
print(frame2)
frame2['debt'] = np.arange(6.)
print(frame2)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN
       year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5
       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0


In [104]:
# assign a column of a pandas data frame with a pandas series for the selected index
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
print(frame2)
frame2['debt'] = val
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0
       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN


In [105]:
# create a new column for a pandas data frame variable with a pandas series
print(frame2)
print(frame2.state == 'Ohio')
print(type(frame2.state == 'Ohio'))
frame2['eastern'] = frame2.state == 'Ohio'
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN
one       True
two       True
three     True
four     False
five     False
six      False
Name: state, dtype: bool
<class 'pandas.core.series.Series'>
       year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False
six    2003  Nevada  3.2   NaN   False


In [106]:
print(frame2)
print(frame2.columns)
del frame2['eastern']
print(frame2)
print(frame2.columns)

       year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False
six    2003  Nevada  3.2   NaN   False
Index(['year', 'state', 'pop', 'debt', 'eastern'], dtype='object')
       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN
Index(['year', 'state', 'pop', 'debt'], dtype='object')


In [107]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [108]:
frame3 = pd.DataFrame(pop)
print(frame3)


      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6


In [112]:
# transpose a pandas data frame variable
print(frame3)
print(frame3.T)
print(type(frame3.T))
frame3.T.describe()

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
        2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6
<class 'pandas.core.frame.DataFrame'>


2000      2001      2002
count   1.0  2.000000  2.000000
mean    1.5  2.050000  3.250000
std     NaN  0.494975  0.494975
min     1.5  1.700000  2.900000
25%     1.5  1.875000  3.075000
50%     1.5  2.050000  3.250000
75%     1.5  2.225000  3.425000
max     1.5  2.400000  3.600000

In [113]:
print(pop)
pd.DataFrame(pop, index=[2001, 2002, 2003])

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}


Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [116]:
print(frame3)
print(frame3['Ohio'][:-1])
print(frame3['Nevada'][:2])
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
print(pdata)
print(type(pdata))
pd.DataFrame(pdata)

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
2000    1.5
2001    1.7
Name: Ohio, dtype: float64
2000    NaN
2001    2.4
Name: Nevada, dtype: float64
{'Ohio': 2000    1.5
2001    1.7
Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
2001    2.4
Name: Nevada, dtype: float64}
<class 'dict'>


Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [117]:
print(frame3)
print(frame3.index)
print(frame3.index.name)
frame3.index.name = 'year'; 
print(frame3.columns)
print(frame3.columns.name)
frame3.columns.name = 'state'
print(frame3)


      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6
Int64Index([2000, 2001, 2002], dtype='int64')
None
Index(['Nevada', 'Ohio'], dtype='object')
None
state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6


In [118]:
print(frame3.index)
print(frame3.index.name)
print(frame3.columns)
print(frame3.columns.name)

Int64Index([2000, 2001, 2002], dtype='int64', name='year')
year
Index(['Nevada', 'Ohio'], dtype='object', name='state')
state


In [120]:
print(frame3.values)
print(type(frame3.values))

[[ nan  1.5]
 [ 2.4  1.7]
 [ 2.9  3.6]]
<class 'numpy.ndarray'>


In [ ]:
frame2.values

### Index Objects

In [122]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
print(obj)
print(obj.index)
print(type(obj.index))
index = obj.index
index
index[1:]

a    0
b    1
c    2
dtype: int64
Index(['a', 'b', 'c'], dtype='object')
<class 'pandas.indexes.base.Index'>


Index(['b', 'c'], dtype='object')

index[1] = 'd'  # TypeError

In [127]:
labels = pd.Index(np.arange(3))
print(labels)
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
print(obj2)
print(obj2.index is labels)
obj2.index == labels

Int64Index([0, 1, 2], dtype='int64')
0    1.5
1   -2.5
2    0.0
dtype: float64
True


array([ True,  True,  True], dtype=bool)

In [133]:
print(frame3)
print(type(frame3))
print(frame3.columns)
print(type(frame3.columns))
print('Ohio' in frame3.columns)
print('Texas' in frame3.columns)
print(2002 in frame3.index)
print(2005 in frame3.index)

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6
<class 'pandas.core.frame.DataFrame'>
Index(['Nevada', 'Ohio'], dtype='object', name='state')
<class 'pandas.indexes.base.Index'>
True
False
True
False


In [135]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
print(dup_labels)
print(type(dup_labels))

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')
<class 'pandas.indexes.base.Index'>


## Essential Functionality

### Reindexing

In [136]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
print(obj)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64


In [137]:
print(obj.index)
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
print(obj2)
print(obj2.index)

Index(['d', 'b', 'a', 'c'], dtype='object')
a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


In [139]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
print(obj3)
print(obj3.index)
print(obj3.reindex(range(6), method='ffill'))
print(obj3.index)

0      blue
2    purple
4    yellow
dtype: object
Int64Index([0, 2, 4], dtype='int64')
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object
Int64Index([0, 2, 4], dtype='int64')


In [140]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
print(frame)
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
print(frame2)

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0


In [141]:
states = ['Texas', 'Utah', 'California']
print(frame.index)
print(frame)
frame.reindex(columns=states)
print(frame.index)
print(frame)

Index(['a', 'c', 'd'], dtype='object')
   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
Index(['a', 'c', 'd'], dtype='object')
   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8


In [148]:
print(states)
print(frame)
print(frame.loc[['a', 'b', 'c', 'd']])
print(frame.loc[['a', 'b', 'c', 'd'], states])
print(frame.loc[['a', 'b', 'c'], states[0:2]])

['Texas', 'Utah', 'California']
   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0
   Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0
   Texas  Utah
a    1.0   NaN
b    NaN   NaN
c    4.0   NaN


### Dropping Entries from an Axis

In [150]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
print(obj)
new_obj = obj.drop('c')
print(new_obj)
print(obj.drop(['d', 'c']))
print(obj)

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
e    4.0
dtype: float64
a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64


In [151]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
print(data)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


In [156]:
print(data)
print(data.drop(['Colorado', 'Ohio']))
print(data.drop(['Colorado', 'Ohio'], axis=0))
print(data)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


In [157]:
print(data)
print(data.drop('two', axis=1))
print(data)
print(data.drop(['two', 'four'], axis='columns'))
print(data)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


In [160]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
print(obj)
print(obj.drop('c', inplace=True))
print(obj)


a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
None
a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64


### Indexing, Selection, and Filtering

In [163]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
print(obj)
print(obj['b'])
print(obj[0])
print(obj[1])
print(obj[2:4])
print(obj[['b', 'a', 'd']])
print(obj[[1, 3]])
print(obj[obj < 2])

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64
1.0
0.0
1.0
c    2.0
d    3.0
dtype: float64
b    1.0
a    0.0
d    3.0
dtype: float64
b    1.0
d    3.0
dtype: float64
a    0.0
b    1.0
dtype: float64


In [165]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [166]:
print(obj)
obj['b':'c'] = 5
print(obj)

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64
a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64


In [167]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
print(data)
print(data['two'])
print(data[['three', 'one']])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64
          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12


In [168]:
print(data[:2])
print(data[data['three'] > 5])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


In [170]:
print(data)
print(data < 5)
data[data < 5] = 0
print(data)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False
          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


#### Selection with loc and iloc

In [172]:
print(data.loc['Colorado', ['two', 'three']])
print(type(data.loc['Colorado', ['two', 'three']]))

two      5
three    6
Name: Colorado, dtype: int64
<class 'pandas.core.series.Series'>


In [173]:
print(data)
print(data.iloc[2, [3, 0, 1]])
print(data.iloc[2])
print(data.iloc[[1, 2], [3, 0, 1]])

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
four    11
one      8
two      9
Name: Utah, dtype: int64
one       8
two       9
three    10
four     11
Name: Utah, dtype: int64
          four  one  two
Colorado     7    0    5
Utah        11    8    9


In [174]:
print(data)
print(data.loc[:'Utah', 'two'])
print(data.iloc[:, :3][data.three > 5])

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64
          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14


### Integer Indexes

ser = pd.Series(np.arange(3.))
ser
ser[-1]

In [175]:
ser = pd.Series(np.arange(3.))

In [176]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [177]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
print(ser2)
print(ser2[-1])

a    0.0
b    1.0
c    2.0
dtype: float64
2.0


In [179]:
print(ser[:1])
print(ser.loc[:1])
print(ser.iloc[:1])

0    0.0
dtype: float64
0    0.0
1    1.0
dtype: float64
0    0.0
dtype: float64


### Arithmetic and Data Alignment

In [181]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
print(s1)
print(s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


In [182]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [183]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(df1)
print(df2)

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0
          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0


In [184]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [185]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
print(df1)
print(df2)
print(df1 - df2)

   A
0  1
1  2
   B
0  3
1  4
    A   B
0 NaN NaN
1 NaN NaN


#### Arithmetic methods with fill values

In [186]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [187]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [188]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [190]:
print(df1)
print(1 / df1)
print(df1.rdiv(1))

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
          a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909
          a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909


In [191]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### Operations between DataFrame and Series

In [193]:
arr = np.arange(12.).reshape((3, 4))
print(arr)
print(arr[0])
print(arr - arr[0])

[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]
[ 0.  1.  2.  3.]
[[ 0.  0.  0.  0.]
 [ 4.  4.  4.  4.]
 [ 8.  8.  8.  8.]]


In [194]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
print(frame)
print(series)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64


In [195]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [197]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
print(frame)
print(series2)
print(frame + series2)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
b    0
e    1
f    2
dtype: int64
          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN


In [199]:
series3 = frame['d']
print(frame)
print(series3)
print(frame.sub(series3, axis='index'))

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64
          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0


### Function Application and Mapping

In [200]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(frame)
print(np.abs(frame))

               b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221
               b         d         e
Utah    0.204708  0.478943  0.519439
Ohio    0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189  1.296221


In [201]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.802165
d    1.684034
e    2.689627
dtype: float64

In [202]:
frame.apply(f, axis='columns')

Utah      0.998382
Ohio      2.521511
Texas     0.676115
Oregon    2.542656
dtype: float64

In [204]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.555730  0.281746 -1.296221
max  1.246435  1.965781  1.393406

### Sorting and Ranking

In [206]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
print(obj)
print(obj.sort_index())
print(obj)

d    0
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    0
dtype: int64
d    0
a    1
b    2
c    3
dtype: int64


In [207]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
print(frame)
print(frame.sort_index())
print(frame.sort_index(axis=1))

       d  a  b  c
three  0  1  2  3
one    4  5  6  7
       d  a  b  c
one    4  5  6  7
three  0  1  2  3
       a  b  c  d
three  1  2  3  0
one    5  6  7  4


In [209]:
print(frame.sort_index(axis=1, ascending=False))
print(frame.sort_index(axis=1, ascending=True))

       d  c  b  a
three  0  3  2  1
one    4  7  6  5
       a  b  c  d
three  1  2  3  0
one    5  6  7  4


In [211]:
obj = pd.Series([4, 7, -3, 2])
print(obj)
print(obj.sort_values())

0    4
1    7
2   -3
3    2
dtype: int64
2   -3
3    2
0    4
1    7
dtype: int64


In [212]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
print(obj)
print(obj.sort_values())

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64
4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64


In [213]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
print(frame)
print(frame.sort_values(by='b'))

   a  b
0  0  4
1  1  7
2  0 -3
3  1  2
   a  b
2  0 -3
3  1  2
0  0  4
1  1  7


In [214]:
print(frame)
print(frame.sort_values(by=['a', 'b']))

   a  b
0  0  4
1  1  7
2  0 -3
3  1  2
   a  b
2  0 -3
0  0  4
3  1  2
1  1  7


In [215]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
print(obj)
print(obj.rank())

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64
0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64


In [217]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [218]:
# Assign tie values the maximum rank in the group
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [220]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
print(frame)
print(frame.rank(axis='columns'))
print(frame.rank(axis=0))
print(frame.rank(axis=1))

   a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5
     a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0
     a    b    c
0  1.5  3.0  2.0
1  3.5  4.0  3.0
2  1.5  1.0  4.0
3  3.5  2.0  1.0
     a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0


### Axis Indexes with Duplicate Labels

In [221]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
print(obj)

a    0
a    1
b    2
b    3
c    4
dtype: int64


In [222]:
obj.index.is_unique

False

In [224]:
print(obj['a'])
print(obj['c'])

a    0
a    1
dtype: int64
4


In [226]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
print(df)
print(df.loc['b'])
print(df.loc['a'])

          0         1         2
a -0.577087  0.124121  0.302614
a  0.523772  0.000940  1.343810
b -0.713544 -0.831154 -2.370232
b -1.860761 -0.860757  0.560145
          0         1         2
b -0.713544 -0.831154 -2.370232
b -1.860761 -0.860757  0.560145
          0         1         2
a -0.577087  0.124121  0.302614
a  0.523772  0.000940  1.343810


## Summarizing and Computing Descriptive Statistics

In [227]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [228]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [229]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [230]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [231]:
df.idxmax()

one    b
two    d
dtype: object

In [232]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [233]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [234]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

conda install pandas-datareader

In [ ]:
price = pd.read_pickle('../../DataSets/pybk022master/examples/yahoo_price.pkl')
volume = pd.read_pickle('../../DataSets/pybk022master/examples/yahoo_volume.pkl')

import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [ ]:
returns = price.pct_change()
returns.tail()

In [ ]:
returns['MSFT'].corr(returns['IBM'])
returns['MSFT'].cov(returns['IBM'])

In [ ]:
returns.MSFT.corr(returns.IBM)

In [ ]:
returns.corr()
returns.cov()

In [ ]:
returns.corrwith(returns.IBM)

In [ ]:
returns.corrwith(volume)

### Unique Values, Value Counts, and Membership

In [ ]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [ ]:
uniques = obj.unique()
uniques

In [ ]:
obj.value_counts()

In [ ]:
pd.value_counts(obj.values, sort=False)

In [ ]:
obj
mask = obj.isin(['b', 'c'])
mask
obj[mask]

In [ ]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

In [ ]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

In [ ]:
result = data.apply(pd.value_counts).fillna(0)
result

## Conclusion

In [ ]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS