In [1]:
# encoding=utf8

# NumPy


In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
type(a)

numpy.ndarray

In [4]:
a.ndim

2

In [5]:
a.shape

(3, 5)

In [6]:
a.size

15

In [12]:
a.dtype, a.dtype.base, a.dtype.byteorder

(dtype('int64'), dtype('int64'), '=')

In [8]:
a.itemsize

8

In [9]:
a.itemset

<function ndarray.itemset>

In [10]:
a.data

In [14]:
b = np.array( [ [1,2], [3,4] ], dtype=complex )
b

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [15]:
type(b)

numpy.ndarray

In [20]:
b.dtype,b.dtype.name,b.itemsize

(dtype('complex128'), 'complex128', 16)

## Create ndarray and initialize with zero

In [21]:
c_zeros = np.zeros( (3,4) )
c_zeros

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

## Create ndarray and initialize with one and specify element type

In [24]:
d_ones = np.ones( (4,3), dtype=np.int32 )
d_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

## Create empty ndarray

In [25]:
e_empties = np.empty( (3,4) ) 
e_empties

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [26]:
e_empties.dtype,e_empties.dtype.name,e_empties.itemsize

(dtype('float64'), 'float64', 8)