In [1]:
# encoding=utf8

# NumPy


In [2]:
import numpy as np
from numpy import pi

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.ndim

2

In [6]:
a.shape

(3, 5)

In [7]:
a.size

15

In [8]:
a.dtype, a.dtype.base, a.dtype.byteorder

(dtype('int64'), dtype('int64'), '=')

In [9]:
a.itemsize

8

In [10]:
a.itemset

<function ndarray.itemset>

In [11]:
a.data

In [12]:
b = np.array( [ [1,2], [3,4] ], dtype=complex )
b

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [13]:
type(b)

numpy.ndarray

In [14]:
b.dtype,b.dtype.name,b.itemsize

(dtype('complex128'), 'complex128', 16)

In [15]:
# Generate some random data
data = np.random.randn(2, 3)
data

array([[ 0.19272572, -1.17050188,  0.52757218],
       [ 0.39798301, -0.78532026,  0.54988857]])

In [16]:
data.ndim, data.shape,data.dtype

(2, (2, 3), dtype('float64'))

# Create ndarray

+ array
+ zeros，zeros_like
+ ones
+ ones_like
+ empty
+ empty_like
+ arange
+ linspace
+ numpy.random.rand
+ numpy.random.randn
+ fromfunction
+ fromfile


In [17]:
np.zeros(10)


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [18]:
np.zeros((3, 6))


array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [19]:
np.empty((2, 3, 2))

array([[[ -1.49166815e-154,  -1.73059911e-077],
        [  2.96439388e-323,   0.00000000e+000],
        [  0.00000000e+000,   1.16095484e-028]],

       [[  7.52736939e+252,   8.95402175e-096],
        [  1.47278596e+179,   9.08367237e+223],
        [  1.16466228e-028,   8.34402701e-309]]])

## Create ndarray and initialize with zero

In [20]:
c_zeros = np.zeros( (3,4) )
c_zeros

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

## Create ndarray and initialize with one and specify element type

In [21]:
d_ones = np.ones( (4,3), dtype=np.int32 )
d_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

## Create empty ndarray

In [22]:
e_empties = np.empty( (3,4) ) 
e_empties

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [23]:
e_empties.dtype,e_empties.dtype.name,e_empties.itemsize

(dtype('float64'), 'float64', 8)

## Create ndarray with np.arange

In [24]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [25]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [26]:
np.linspace( 0, 2, 9 )       

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [27]:
x = np.linspace( 0, 2*pi, 100 )  
x

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

## Create ndarray with list

In [28]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [29]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Create ndarray from function

In [30]:
def createFromFunc(x,y):
    return x+y

In [31]:
arr3 = np.fromfunction(createFromFunc,(5,4),dtype=int)
arr3

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [32]:
arr3[:,1]

array([1, 2, 3, 4, 5])

## Data Types for ndarrays

In [33]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1


array([ 1.,  2.,  3.])

In [34]:
arr1.dtype,

(dtype('float64'),)

In [35]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [36]:
arr2.dtype

dtype('int32')

In [37]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [38]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [39]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [40]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [41]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([0, 0, 1, 0, 2, 0, 3, 0], dtype=uint32)

## Print ndarray

In [42]:
a = np.arange(6)    
print(a)

[0 1 2 3 4 5]


In [43]:
a

array([0, 1, 2, 3, 4, 5])

In [44]:
b = np.arange(12).reshape(4,3)  
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [46]:
c = np.arange(24).reshape(2,3,4) 
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [47]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [48]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [49]:
#np.set_printoptions(threshold='nan')
#np.arange(10000).reshape(100,100)

# Change Shape

In [50]:
arr = np.floor(10*np.random.random(3,4))
print(arr)

TypeError: random_sample() takes at most 1 positional argument (2 given)