In [1]:
# encoding=utf8

# NumPy Basics

In [1]:
import matplotlib.pyplot as plt
import numpy as np

from numpy.linalg import inv, qr
from numpy import newaxis

from random import normalvariate
import random

np.random.seed(12345)
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

## Transformation

### Stacking by Column

In [11]:
a = np.floor(10*np.random.random(10))
b = np.floor(10*np.random.random(10))
a,b

(array([ 8.,  5.,  9.,  7.,  3.,  0.,  0.,  4.,  7.,  8.]),
 array([ 6.,  4.,  9.,  3.,  2.,  6.,  0.,  6.,  6.,  1.]))

In [12]:
np.column_stack((a,b)) 

array([[ 8.,  6.],
       [ 5.,  4.],
       [ 9.,  9.],
       [ 7.,  3.],
       [ 3.,  2.],
       [ 0.,  6.],
       [ 0.,  0.],
       [ 4.,  6.],
       [ 7.,  6.],
       [ 8.,  1.]])

In [14]:
a[:,newaxis]

array([[ 8.],
       [ 5.],
       [ 9.],
       [ 7.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 4.],
       [ 7.],
       [ 8.]])

In [13]:
np.column_stack((a[:,newaxis],b[:,newaxis])) 

array([[ 8.,  6.],
       [ 5.,  4.],
       [ 9.,  9.],
       [ 7.,  3.],
       [ 3.,  2.],
       [ 0.,  6.],
       [ 0.,  0.],
       [ 4.,  6.],
       [ 7.,  6.],
       [ 8.,  1.]])

In [15]:
np.vstack((a[:,newaxis],b[:,newaxis])) 

array([[ 8.],
       [ 5.],
       [ 9.],
       [ 7.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 4.],
       [ 7.],
       [ 8.],
       [ 6.],
       [ 4.],
       [ 9.],
       [ 3.],
       [ 2.],
       [ 6.],
       [ 0.],
       [ 6.],
       [ 6.],
       [ 1.]])

## Conclusion