In [ ]:
# encoding=utf8

# Linear Regression Analysis

Linear Regression Analysis Matrix Approach(Both Simple and Multiple)

y=b0 + b1x1 + b2x2 + ........ +bn*xn

In [1]:
#Simple Linear regression (y=b0 + b1*x)
from numpy import *
points=genfromtxt("../../DataSets/pybk017master/data.csv",delimiter=",")
print(points)

[[          nan           nan]
 [  32.50234527   31.70700585]
 [  53.42680403   68.77759598]
 [  61.53035803   62.5623823 ]
 [  47.47563963   71.54663223]
 [  59.81320787   87.23092513]
 [  55.14218841   78.21151827]
 [  52.21179669   79.64197305]
 [  39.29956669   59.17148932]
 [  48.10504169   75.3312423 ]
 [  52.55001444   71.30087989]
 [  45.41973014   55.16567715]
 [  54.35163488   82.47884676]
 [  44.1640495    62.00892325]
 [  58.16847072   75.39287043]
 [  56.72720806   81.43619216]
 [  48.95588857   60.72360244]
 [  44.68719623   82.89250373]
 [  60.29732685   97.37989686]
 [  45.61864377   48.84715332]
 [  38.81681754   56.87721319]
 [  66.18981661   83.87856466]
 [  65.41605175  118.5912173 ]
 [  47.48120861   57.25181946]
 [  41.57564262   51.39174408]
 [  51.84518691   75.38065167]
 [  59.37082201   74.76556403]
 [  57.31000344   95.45505292]
 [  63.61556125   95.22936602]
 [  46.73761941   79.05240617]
 [  50.55676015   83.43207142]
 [  52.22399609   63.35879032]
 [  35.5

In [2]:
points=genfromtxt('../../DataSets/pybk017master/data.csv',delimiter=",")
points=delete(points,(0),axis=0)
y_actual=array(points[:,len(points[0])-1])
points[:,len(points[0])-1]=1
y_actual.resize(len(points),1)
beta=matrix(linalg.lstsq(points,y_actual)[0])
beta.resize(len(points[0]),1)
y_pred=dot(points,beta)
pro=(y_actual-y_pred)
error=sum(multiply(pro,pro))/len(points)
print("b0=",float(beta[len(beta)-1]),sep="")
for i in range(len(beta)-1):
    print("b",i+1,"=",float(beta[i]),sep="")
print("Error:",error)  

b0=7.991020985734434
b1=1.322431022687868
Error: 110.257383449


In [3]:
#Multiple Linear regression
points=genfromtxt("../../DataSets/pybk017master/pdata.csv",delimiter=",")
print(points)

[[  nan   nan   nan   nan]
 [  73.   80.   75.  152.]
 [  93.   88.   93.  185.]
 [  89.   91.   90.  180.]
 [  96.   98.  100.  196.]
 [  73.   66.   70.  142.]
 [  53.   46.   55.  101.]
 [  69.   74.   77.  149.]
 [  47.   56.   60.  115.]
 [  87.   79.   90.  175.]
 [  79.   70.   88.  164.]
 [  69.   70.   73.  141.]
 [  70.   65.   74.  141.]
 [  93.   95.   91.  184.]
 [  79.   80.   73.  152.]
 [  70.   73.   78.  148.]
 [  93.   89.   96.  192.]
 [  78.   75.   68.  147.]
 [  81.   90.   93.  183.]
 [  88.   92.   86.  177.]
 [  78.   83.   77.  159.]
 [  82.   86.   90.  177.]
 [  86.   82.   89.  175.]
 [  78.   83.   85.  175.]
 [  76.   83.   71.  149.]
 [  96.   93.   95.  192.]]


In [4]:
points=genfromtxt('../../DataSets/pybk017master/pdata.csv',delimiter=",")
points=delete(points,(0),axis=0)
y_actual=array(points[:,len(points[0])-1])
points[:,len(points[0])-1]=1
y_actual.resize(len(points),1)
beta=matrix(linalg.lstsq(points,y_actual)[0])
beta.resize(len(points[0]),1)
y_pred=dot(points,beta)
pro=(y_actual-y_pred)
error=sum(multiply(pro,pro))/len(points)
print("b0=",float(beta[len(beta)-1]),sep="")
for i in range(len(beta)-1):
    print("b",i+1,"=",float(beta[i]),sep="")
print("Error:",error) 

b0=-4.3361024012402645
b1=0.35593821866182046
b2=0.5425187576187032
b3=1.1674442162822212
Error: 5.73780714414
