In [1]:
# encoding=utf8

# Scikit-learn: Data Preparation Examples

+ 标准化
+ 数据最大最小缩放处理
+ 正则化
+ 特征二值化
+ 数据缺失值处理

# scale标准化示例

In [6]:
from sklearn import preprocessing

In [7]:
import numpy as np

In [8]:
x = np.array([[ 0, -1.,  0],[ -1, 4.,  -1.0],[ 0, -1.,  0]])

In [9]:
x_scaled = preprocessing.scale(X)

In [10]:
x_scaled

array([[ 0.70710678, -0.70710678,  0.70710678],
       [-1.41421356,  1.41421356, -1.41421356],
       [ 0.70710678, -0.70710678,  0.70710678]])

In [12]:
x_scaled.mean(axis=0)

array([ -7.40148683e-17,   7.40148683e-17,  -7.40148683e-17])

In [13]:
x_scaled.std(axis=0)

array([ 1.,  1.,  1.])

# StandardScaler示例

In [16]:
scaler = preprocessing.StandardScaler().fit(X)

In [17]:
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [18]:
scaler.mean_

array([-0.33333333,  0.66666667, -0.33333333])

In [19]:
scaler.scale_    

array([ 0.47140452,  2.3570226 ,  0.47140452])

In [20]:
scaler.transform(X) 

array([[ 0.70710678, -0.70710678,  0.70710678],
       [-1.41421356,  1.41421356, -1.41421356],
       [ 0.70710678, -0.70710678,  0.70710678]])

In [21]:
scaler.transform([[-1.,  1., 0.]]) 

array([[-1.41421356,  0.14142136,  0.70710678]])

# MinMaxScaler

In [22]:
min_max_scaler = preprocessing.MinMaxScaler()

In [23]:
X_minMax = min_max_scaler.fit_transform(X)

In [24]:
X_minMax

array([[ 1.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  1.]])

# Scaling data with outliers

In [25]:
#http://scikit-learn.org/stable/modules/preprocessing.html#scaling-data-with-outliers

# 正则化Normalization

In [26]:
X_normalized = preprocessing.normalize(X, norm='l2')

In [27]:
X_normalized     

array([[ 0.        , -1.        ,  0.        ],
       [-0.23570226,  0.94280904, -0.23570226],
       [ 0.        , -1.        ,  0.        ]])

# 二值化Binarization

In [28]:
binarizer = preprocessing.Binarizer().fit(X) 

In [29]:
binarizer

Binarizer(copy=True, threshold=0.0)

In [30]:
binarizer.transform(X)

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  0.]])

# Encoding categorical features

In [31]:
#http://scikit-learn.org/stable/modules/preprocessing.html#encoding-categorical-features

# Imputation of missing values

缺失值处理

In [38]:
#http://scikit-learn.org/stable/modules/preprocessing.html#imputation-of-missing-values
import numpy as np

In [33]:
from sklearn.preprocessing import Imputer

In [34]:
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)

In [35]:
imp.fit([[1, 2], [np.nan, 3], [7, 6]])

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [36]:
X = [[np.nan, 2], [6, np.nan], [7, 6]]

In [37]:
print(imp.transform(X))   

[[ 4.          2.        ]
 [ 6.          3.66666667]
 [ 7.          6.        ]]
